version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  redis:
    image: redis
    ports:
      - "6379:6379"

  api-server:
    build: ./api-server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis

  worker:
    build: ./worker
    depends_on:
      - mongo
      - redis

  vendor-sync:
    build: ./vendor-sync
    ports:
      - "5000:5000"

  vendor-async:
    build: ./vendor-async
    ports:
      - "5001:5001"
